version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: heart_attack
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  jupyter:
    image: myjupyter:local
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    depends_on:
      - db
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work

volumes:
  pgdata:
