FROM jupyter/base-notebook:python-3.11.6

WORKDIR /home/jovyan/work

COPY requirements.txt /tmp/requirements.txt

USER root
RUN apt-get update && apt-get install -y --no-install-recommends gcc build-essential \
 && pip install --upgrade pip setuptools wheel \
 && pip install --no-cache-dir -r /tmp/requirements.txt \
 && apt-get remove -y gcc build-essential && apt-get autoremove -y \
 && rm -rf /var/lib/apt/lists/* /tmp/requirements.txt

USER $NB_UID
